---

- name: ensure .ssh directory exists
  file:
    path: "{{spark_user_home}}/.ssh"
    state: directory
    mode: 0700
    owner: "{{spark_user}}"
    group: "{{spark_user}}"

- name: slurp the ssh key
  slurp:
    src: "{{spark_user_home}}/.ssh/id_rsa.pub"
  delegate_to: "{{spark_master}}"
  register: spark_ssh_key

- name: copy public key from master
  copy:
    dest: "{{spark_user_home}}/.ssh/master_id_rsa.pub"
    content: "{{spark_ssh_key.content | b64decode}}"
  register: spark_ssh_key_copied

- name: install public key in authorized_keys
  shell: "cat {{spark_user_home}}/.ssh/master_id_rsa.pub >> {{spark_user_home}}/.ssh/authorized_keys"
  when: spark_ssh_key_copied.changed

- name: fix permissions on authorized_keys
  file:
    path: "{{spark_user_home}}/.ssh/authorized_keys"
    mode: 0600
    owner: "{{spark_user}}"
    group: "{{spark_user}}"
